apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: utsavanand2@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-cert
    solvers:
    - http01:
        ingress:
          class: nginx