apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: blinkt
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: blinkt
  template:
    metadata:
      labels:
        app: blinkt
    spec:
      containers:
      - name: blinkt
        image:  utsavanand2/blinktserver:latest
        imagePullPolicy: "Always"
        ports:
          - containerPort: 80
            protocol: TCP
        volumeMounts:
        - mountPath: /sys
          name: sys-tree
      volumes:
      - name: sys-tree
        hostPath:
          path: /sys

