name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - 
        name: Get tags
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      -
        name: Login to OpenFaaS Gateway
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} \
                      -g ${{ secrets.OPENFAAS_GATEWAY }}
      - 
        name: Install npm modules
        run: make install-dep
      - 
        name: Build the React App
        run: make build-react-app
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - 
        name: Run shrinkwrap build
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f birthday-func/birthday-func.yml --shrinkwrap
      - 
        name: Set Username/Repo as ENV vars
        run: |
          echo "USER_REPO"=$(echo "$GITHUB_REPOSITORY" | awk '{print tolower($1)}' | sed -e "s/:refs//") >> $GITHUB_ENV
      - 
        name: List Dir contents
        run: ls -lah && ls -lah ./build/birthday-func/
      -
        name: Build and Push container images
        uses: docker/build-push-action@v2
        with:
          context: ./build/birthday-func/birthday-func/
          file: ./build/birthday-func/birthday-func/Dockerfile
          platforms: linux/arm/v7
          labels: org.opencontainers.image.source=https://github.com/${{ env.USER_REPO }}
          push: true
          tags: |
            ghcr.io/utsavanand2/birthday-func:${{ github.sha }}
            ghcr.io/utsavanand2/birthday-func:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/utsavanand2/birthday-func:latest
      -
        name: Deploy the function
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: deploy -f birthday-func/birthday-func.yml
